CREATE TABLE IF NOT EXISTS AIRFLOW.DEV.STG_STOCK_HISTORY_3_new
LIKE US_STOCK_DAILY.DCCM.STOCK_HISTORY;

CREATE TABLE IF NOT EXISTS AIRFLOW.DEV.STG_COMPANY_PROFILE_3_new
LIKE US_STOCK_DAILY.DCCM.COMPANY_PROFILE;

CREATE TABLE IF NOT EXISTS AIRFLOW.DEV.STG_SYMBOLS_3_new
LIKE US_STOCK_DAILY.DCCM.SYMBOLS;